export const symptoms = ['ban đỏ', 'buồn muốn khóc', 'buồn ngủ', 'buồn nôn', 'buồn nôn và nôn mửa', 'bản quan sát nhiệt độ nghiêm ngặt', 'bất tỉnh', 'bất động'
    , 'bệnh nhân không tuân thủ bác sĩ', 'bị sưng', 'bốc hoả', 'choáng váng'
    , 'chuyển giới', 'chuột rút', 'chán ăn', 'chép môi', 'chóng mặt'
    , 'chóng mặt kiểu xoay vòng', 'chóng mặt thế đứng', 'chưa từng có thai'
    , 'chảy dãi', 'chảy máu âm đạo', 'chảy nước mũi', 'chảy nước mũi sau'
    , 'chậm về thể chất và tinh thần', 'chứng co giật thần kinh cục bộ'
    , 'chứng giật cơ', 'chứng khó thở', 'chứng mất khứu giác', 'chứng sợ ánh sáng'
    , 'chứng sợ âm thanh', 'chứng tim to', 'chứng to lách', 'chứng xanh tím da'
    , 'co thắt không tự chủ', 'co thắt tâm vị'
    , 'các yếu tố làm trầm trọng thêm triệu chứng khác', 'cánh mũi phập phồng'
    , 'cáu kỉnh', 'có biểu hiện cho thấy hoạt động vận động tăng lên'
    , 'có các đặc trưng của sóng r', 'có tiền sử mất nhận thức', 'có tín ngưỡng'
    , 'có đường Stahli', 'căng trương lực', 'cơ cứng', 'cơn aura', 'cơn co thắt'
    , 'cơn khóc lặng', 'cơn động kinh', 'cơn động kinh co cứng'
    , 'cảm giác bất thường', 'cảm giác choáng váng', 'cảm giác châm chích'
    , 'cảm giác khác thường', 'cảm giác khó chịu', 'cảm giác kiến bò'
    , 'cảm giác nóng rát', 'cảm giác nặng nề', 'cảm giác đau nhói'
    , 'cảm thấy chán nản', 'cảm thấy nóng/ hơi sốt', 'cảm thấy tuyệt vọng'
    , 'cổ trướng', 'cục cứng ở vú', 'cứng ở gáy', 'cử động chậm chạp'
    , 'cực kì kiệt sức', 'da bị macerated', 'da ẩm ướt', 'di căn'
    , 'dung tích hồng cầu giảm', 'dáng đi không vững'
    , 'dương tính với xét nghiệm guaiac'
    , 'dương tính với xét nghiệm máu ẩn trong phân', 'dấu hiệu Murphy'
    , 'dấu hiệu của hội chứng ngoại tháp', 'dấu hiệu liên quan tới tim mạch'
    , 'dị cảm', 'gan to', 'gia đình bất hoà', 'giãn đồng tử', 'giảm albumin máu'
    , 'giảm chức năng vận động', 'giảm cân', 'giảm protein trong máu'
    , 'giảm trương lực', 'giảm trương lực cơ', 'hay dùng từ mới', 'hay uống sữa'
    , 'hiện tượng liên quan tới tim mạch', 'ho', 'ho có đờm', 'ho khan'
    , 'ho ra máu', 'ho ăng ẳng', 'hoảng loạn', 'hoảng sợ', 'huyết áp thấp'
    , 'huyết động ổn định', 'hành vi lạm dụng bằng lời nói', 'hôn mê'
    , 'hạ canxi máu', 'hạ huyết áp thế đứng', 'hạ kali trong máu'
    , 'hạ natri trong máu', 'hạ oxi trong máu', 'hạ thân nhiệt', 'hắt hơi'
    , 'hồi hộp', 'hội chứng bất lực ngôn ngữ', 'hội chứng cai rượu'
    , 'hội chứng ngủ nhiều', 'hội chứng qt dài', 'hội chứng suy giảm sức khoẻ'
    , 'incoherent', 'khàn giọng', 'khát nước', 'khó chịu', 'khó chịu ở ngực'
    , 'khó khăn trong việc tiểu tiện', 'khó thở', 'khó thở khi gắng sức'
    , 'khó thở khi nằm', 'khó tiểu', 'không có tiền sử dị ứng thuốc'
    , 'không có triệu chứng bệnh', 'không dung nạp thực phẩm', 'không hút thuốc'
    , 'không khoẻ', 'không phối hợp tay chân', 'không thay đổi trạng thái'
    , 'không vui vẻ', 'khập khiễng', 'kiểm tra độ rung', 'kiệt sức', 'kém ăn'
    , 'kích động', 'liệt nhẹ', 'liệt nhẹ chi dưới', 'liệt nửa người'
    , 'liệt thần kinh mặt', 'liệt todd', 'lo lắng', 'lo âu', 'loá mắt'
    , 'loạn cận ngôn', 'loạn liên động', 'lãnh đạm', 'lệch trung thất'
    , 'lớn nhĩ trái', 'mang thai 10 lần', 'mang thai 2 lần', 'mang thai một lần'
    , 'muốn tự tử', 'máu đơn dòng', 'mô sẹo', 'mũi khụt khịt', 'mạch đảo', 'mất bù'
    , 'mất mạch', 'mất ngủ', 'mất nhận thức', 'mất nhận thức ', 'mất thăng bằng'
    , 'mất thị lực một bên thị trường ở cả hai mắt', 'mất ý thức'
    , 'mất điều hòa vận động', 'mặt tròn do hội chứng cushing', 'mệt', 'mệt mỏi'
    , 'mệt mỏi mạn tính', 'mọc thiếu răng', 'mỏi chân', 'mờ mắt', 'mức dịch khí'
    , 'nang niệu', 'nghẹt mũi', 'nghẹt thở', 'ngáy', 'ngất xỉu', 'ngồi xe lăn'
    , 'ngộ độc', 'ngủ nhiều', 'ngứa', 'nhược trương', 'nhạy cảm với âm thanh'
    , 'nhịp thở nhanh', 'nhịp tim chậm', 'nhọt', 'nhức'
    , 'những thay đổi của bệnh khí phế thũng', 'nín thở'
    , 'nói không liên kết với nhau', 'nói lắp bắp', 'nói năng lan man', 'nôn'
    , 'nôn mửa', 'nôn nghén nặng', 'nôn vọt', 'nằm liệt giường', 'nốt heberden'
    , 'nốt phổi', 'nổi đốm đỏ', 'phá thai', 'phân bố trọng lượng cơ thể thay đổi'
    , 'phân có kích thước nhỏ', 'phân cứng khác thường', 'phân màu vàng'
    , 'phân trong trực tràng', 'phì đại tuyến tiền liệt ', 'phản xạ ọe'
    , 'phản ứng có hại', 'phấn khích', 'phối hợp vận động bất thường'
    , 'protein niệu', 'rhd dương', 'run khi nghỉ ', 'run rẩy', 'rên rỉ', 'rậm lông'
    , 'rối loạn nhịp xoang', 'rối loạn tăng tiết mồ hôi', 'sinh con 2 lần'
    , 'sinh non', 'suy dinh dưỡng', 'suy giảm nhận thức', 'suy hô hấp', 'suy nhược'
    , 'suy nhược ', 'suy tư thế vận động', 'sóng t đảo ngược', 'sưng tấy'
    , 'sỏi thận di chuyển', 'sốt', 'sổ mũi', 'sợ bị vấp ngã', 'sử dụng nội tiết tố'
    , 'sử dụng đồ uống có cồn quá mức', 'sững sờ', 'thai nhi ngôi mông', 'thai to'
    , 'thay đổi trạng thái tâm thần', 'thiếu tập trung', 'thuận hai tay'
    , 'thái độ khác thường', 'thấy khó khăn', 'thể trạng của hội chứng cushing'
    , 'thở gấp', 'thở hổn hển', 'thở khò khè', 'thở khó', 'thở nông nhanh'
    , 'thức dậy sớm', 'thừa cân', 'tiêu chảy', 'tiếng cọ màng ngoài tim'
    , 'tiếng dê kêu', 'tiếng phụt tâm thu', 'tiếng ran', 'tiếng ran ẩm khô'
    , 'tiếng thở nhỏ dần', 'tiếng thở rít', 'tiếng tâm thu', 'tiếng ọc ọc'
    , 'tiểu chậm', 'tiểu gấp', 'tiểu không tự chủ', 'tiểu nhiều', 'tiểu ra khí'
    , 'tiểu ra phân', 'tiểu ít', 'to gan lách', 'triệu chứng báo trước bệnh'
    , 'triệu chứng giảm chuyển hoá', 'tràn dịch khí màng phổi'
    , 'tràn trề năng lượng', 'trào ngược sau khi nuốt', 'tuyến tiền liệt mềm'
    , 'tác dụng bất lợi', 'tái nhợt', 'táo bón', 'tê liệt', 'tê tay'
    , 'tình trạng không sốt', 'tích trữ rượu', 'tính tình thất thường'
    , 'tăng bạch cầu mono', 'tăng các men transaminase ', 'tăng cân'
    , 'tăng cảm giác', 'tăng kali trong máu', 'tăng thông khí', 'tăng động'
    , 'tĩnh mạch cổ nổi', 'tư thế khác thường', 'tế bào bất thường'
    , 'tế bào tế bào bất thường', 'tế bào ung thư xâm nhập', 'tổn thương nang'
    , 'tức ngực', 'tự sát', 'uể oải', 'vi khuẩn abscess', 'viêm mô mềm'
    , 'vàng củng mạc', 'vô gia cư', 'vùng da đỏ', 'vấp ngã', 'vật vã', 'vết dát'
    , 'vết sẹo', 'vết thâm tím', 'vết thương tổn', 'vết trầy xước', 'vỡ ối tự phát'
    , 'vụng về', 'xuất hiện sóng q', 'xuất huyết', 'xuất huyết tử cung nhiều'
    , 'xây xẩm mặt mày', 'xơ vữa', 'yếu ớt', 'ác mộng', 'âm ruột giảm', 'âm thổi'
    , 'âm thổi toàn tâm thu', 'âm thở bất thường', 'ít vận động', 'ù tai'
    , 'ý nghĩ giết người', 'ý thức rõ ràng', 'ăn nhanh no', 'đau bàn chân'
    , 'đau bộc phát', 'đau bụng', 'đau bụng colic', 'đau bụng cấp'
    , 'đau chân khi đi bộ', 'đau cơ', 'đau cổ', 'đau dữ dội', 'đau họng'
    , 'đau khi chạm vào', 'đau khi giao hợp', 'đau khi nuốt', 'đau khớp'
    , 'đau lưng', 'đau màn phổi', 'đau một bên', 'đau ngực', 'đau ngực ', 'đau nhức'
    , 'đau nhức nhối khắp cơ thể', 'đau thần kinh tọa', 'đau thắt lưng'
    , 'đau thắt ngực', 'đau trực tràng do chuột rút', 'đau tức ngực', 'đau âm ỉ'
    , 'đau đa cơ', 'đau đầu', 'đau ở chi dưới', 'đau ở các chi', 'đau ở góc thận'
    , 'đi chệnh choạng', 'đi lảo đảo', 'đi vệ sinh ra máu'
    , 'điện tâm đồ st chênh lênh', 'điện tâm đồ st chênh xuống', 'đái dầm'
    , 'đái ra máu', 'đói bụng', 'đảo mắt', 'đầy bụng', 'đầy hơi', 'đẩy lùi xương'
    , 'đỏ da ở một vùng', 'đỏ mặt', 'đồng nhiễm khuẩn', 'đồng tử thu nhỏ'
    , 'đổ mồ hôi', 'đổ mồ hôi nhiều', 'đổ mồ hôi về đêm', 'độ mờ phổi giảm'
    , 'động kinh rung giật cơ', 'đờm có bọt', 'đờm có mủ nhầy', 'đờm vàng'
    , 'đờm xanh', 'ưu trương', 'ảo ảnh thính giác', 'ảo ảnh thị giác'
    , 'ảo ảnh tiếng nói', 'ớn lạnh', 'ợ nóng', 'ức chế hô hấp']